Add `timeout` feature
holepunchto/bare-tcp pull request #6
Opened 2024-06-24 18:49 UTC by yassernasc

Following nodejs docs specification:

- socket.`timeout` informing the current timeout ms value.
- 'timeout' event, and optional callback at `setTimeout`
- timeout option at `createConnection`

---

I set to refresh the timeout at `_onread` and `_onwrite`. IDK if it's enough.

---

One thing that I noticed that bare-tcp is behaving differently to nodejs in my experience is: the tests cannot be closed (the sample server keeps listening) if the `server connection socket` is not destroyed manually, that's why I am collecting it at lines like: `const server = createServer((s) => _sockets.push(s)).listen()`.

2024-06-25 16:17 UTC, kasperisager requested changes
Looks good, just some small nits! 👌

2024-06-25 16:17 UTC, kasperisager commented on index.js
> +    this._timeout = null
```suggestion
    this._timer = null
```

To avoid the `timout` and `_timeout` clash, which is a little confusing.

2024-06-25 16:17 UTC, kasperisager commented on index.js
> +    this._timeout = setTimeout(() => this.emit('timeout'), ms)
```suggestion
    this._timer = setTimeout(() => this.emit('timeout'), ms)
```

2024-06-25 16:17 UTC, kasperisager commented on index.js
> +    if (ontimeout) this.on('timeout', ontimeout)
```suggestion
    if (ontimeout) this.once('timeout', ontimeout)
```

So it'll only trigger when _this_ timeout is reached, not necessarily any future timeouts.

2024-06-25 18:11 UTC, yassernasc commented
Well-explained comments, I've applied all suggestions. I didn't know about the QuickJS issue, I'll keep an eye on that.

2024-06-25 18:21 UTC, kasperisager requested changes
The remaining test cases need to end the server side of the connection as well and then it's good to go! 👍

2024-06-26 09:02 UTC, kasperisager commented
Good point, I observed the same thing! 👀 The issue was that the stream state got stuck as the side that closed immediately never started reading, resulting in `close` never emitting. I added an explicit `socket.resume()` after `socket.end()`, which got the stream state unstuck. A noop `data` listener would also have worked.

@mafintosh Is this a feature or a bug? Node.js behaves the same so my guess is the former.

2024-06-26 09:05 UTC, mafintosh commented
Feaure! You HAVE to drain the the stream or .destroy it yourself (or the remote destroys it)

2024-06-26 09:06 UTC, kasperisager commented
Perfect, thanks!

2024-06-26 09:19 UTC, kasperisager requested changes
One thing I nearly forgot that https://nodejs.org/api/net.html#socketsettimeouttimeout-callback mentions: `socket.setTimeout(0)` should disable the idle timer.

2024-06-26 16:34 UTC, kasperisager approved these changes
Fantastic! 👏

2024-06-26 16:34 UTC, merged